"""Dry-run and real-write state values for CD5 price programming."""

from __future__ import annotations

from enum import StrEnum


class PriceDryRunState(StrEnum):
    PUMP_NOT_PROGRAMMED = "PUMP_NOT_PROGRAMMED"
    PRICE_BLOCK_BUILT = "PRICE_BLOCK_BUILT"
    PRICE_BLOCK_REVIEW_PENDING = "PRICE_BLOCK_REVIEW_PENDING"
    PRICE_BLOCK_APPROVED_NOT_TRANSMITTED = "PRICE_BLOCK_APPROVED_NOT_TRANSMITTED"
    FILLING_COMPLETE_EXPECTED = "FILLING_COMPLETE_EXPECTED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"


class PriceWriteState(StrEnum):
    PUMP_NOT_PROGRAMMED = "PUMP_NOT_PROGRAMMED"
    PRICE_BLOCK_BUILT = "PRICE_BLOCK_BUILT"
    CD5_AUTHORIZED_FOR_SINGLE_WRITE = "CD5_AUTHORIZED_FOR_SINGLE_WRITE"
    CD5_TRANSMITTED = "CD5_TRANSMITTED"
    ACK_RECEIVED = "ACK_RECEIVED"
    ACK_TIMEOUT = "ACK_TIMEOUT"
    FILLING_COMPLETE_VERIFIED = "FILLING_COMPLETE_VERIFIED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"


class ResetWriteState(StrEnum):
    FILLING_COMPLETE = "FILLING_COMPLETE"
    RESET_BLOCK_BUILT = "RESET_BLOCK_BUILT"
    RESET_AUTHORIZED_FOR_SINGLE_WRITE = "RESET_AUTHORIZED_FOR_SINGLE_WRITE"
    RESET_TRANSMITTED = "RESET_TRANSMITTED"
    ACK_RECEIVED = "ACK_RECEIVED"
    ACK_TIMEOUT = "ACK_TIMEOUT"
    RESET_VERIFIED = "RESET_VERIFIED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"


class AuthorizeWriteState(StrEnum):
    RESET = "RESET"
    AUTHORIZE_BLOCK_BUILT = "AUTHORIZE_BLOCK_BUILT"
    AUTHORIZE_AUTHORIZED_FOR_SINGLE_WRITE = (
        "AUTHORIZE_AUTHORIZED_FOR_SINGLE_WRITE"
    )
    AUTHORIZE_TRANSMITTED = "AUTHORIZE_TRANSMITTED"
    ACK_RECEIVED = "ACK_RECEIVED"
    ACK_TIMEOUT = "ACK_TIMEOUT"
    AUTHORIZED_VERIFIED = "AUTHORIZED_VERIFIED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"
