"""Dry-run and real-write state values for CD5 price programming."""

from __future__ import annotations

from enum import StrEnum


class PriceDryRunState(StrEnum):
    PUMP_NOT_PROGRAMMED = "PUMP_NOT_PROGRAMMED"
    PRICE_BLOCK_BUILT = "PRICE_BLOCK_BUILT"
    PRICE_BLOCK_REVIEW_PENDING = "PRICE_BLOCK_REVIEW_PENDING"
    PRICE_BLOCK_APPROVED_NOT_TRANSMITTED = "PRICE_BLOCK_APPROVED_NOT_TRANSMITTED"
    FILLING_COMPLETE_EXPECTED = "FILLING_COMPLETE_EXPECTED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"


class PriceWriteState(StrEnum):
    PUMP_NOT_PROGRAMMED = "PUMP_NOT_PROGRAMMED"
    FILLING_COMPLETE = "FILLING_COMPLETE"  # re-price path (already CLOSED)
    PRICE_BLOCK_BUILT = "PRICE_BLOCK_BUILT"
    CD5_AUTHORIZED_FOR_SINGLE_WRITE = "CD5_AUTHORIZED_FOR_SINGLE_WRITE"
    CD5_TRANSMITTED = "CD5_TRANSMITTED"
    ACK_RECEIVED = "ACK_RECEIVED"
    ACK_TIMEOUT = "ACK_TIMEOUT"
    FILLING_COMPLETE_VERIFIED = "FILLING_COMPLETE_VERIFIED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"


class ResetWriteState(StrEnum):
    FILLING_COMPLETE = "FILLING_COMPLETE"
    RESET_BLOCK_BUILT = "RESET_BLOCK_BUILT"
    RESET_AUTHORIZED_FOR_SINGLE_WRITE = "RESET_AUTHORIZED_FOR_SINGLE_WRITE"
    RESET_TRANSMITTED = "RESET_TRANSMITTED"
    ACK_RECEIVED = "ACK_RECEIVED"
    ACK_TIMEOUT = "ACK_TIMEOUT"
    RESET_VERIFIED = "RESET_VERIFIED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"


class ResetDiagnosticResult(StrEnum):
    """Final CD1 RESET diagnostic outcome for lab evidence."""

    RESET_DIAGNOSTIC_ACK_STATE_CHANGED = "RESET_DIAGNOSTIC_ACK_STATE_CHANGED"
    RESET_DIAGNOSTIC_ACK_STATE_UNCHANGED = "RESET_DIAGNOSTIC_ACK_STATE_UNCHANGED"
    RESET_DIAGNOSTIC_NAK = "RESET_DIAGNOSTIC_NAK"
    RESET_DIAGNOSTIC_TIMEOUT = "RESET_DIAGNOSTIC_TIMEOUT"
    RESET_DIAGNOSTIC_REFUSED = "RESET_DIAGNOSTIC_REFUSED"
    RESET_DIAGNOSTIC_PROTOCOL_ERROR = "RESET_DIAGNOSTIC_PROTOCOL_ERROR"


class AuthorizeWriteState(StrEnum):
    RESET = "RESET"
    AUTHORIZE_BLOCK_BUILT = "AUTHORIZE_BLOCK_BUILT"
    AUTHORIZE_AUTHORIZED_FOR_SINGLE_WRITE = (
        "AUTHORIZE_AUTHORIZED_FOR_SINGLE_WRITE"
    )
    AUTHORIZE_TRANSMITTED = "AUTHORIZE_TRANSMITTED"
    ACK_RECEIVED = "ACK_RECEIVED"
    ACK_TIMEOUT = "ACK_TIMEOUT"
    AUTHORIZED_VERIFIED = "AUTHORIZED_VERIFIED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"


class Cd2ResetWriteState(StrEnum):
    FILLING_COMPLETE = "FILLING_COMPLETE"
    NOZZLE_OUT = "NOZZLE_OUT"
    CD2_RESET_BLOCK_BUILT = "CD2_RESET_BLOCK_BUILT"
    CD2_RESET_AUTHORIZED_FOR_SINGLE_WRITE = (
        "CD2_RESET_AUTHORIZED_FOR_SINGLE_WRITE"
    )
    CD2_RESET_TRANSMITTED = "CD2_RESET_TRANSMITTED"
    ACK_RECEIVED = "ACK_RECEIVED"
    ACK_TIMEOUT = "ACK_TIMEOUT"
    RESET_VERIFIED = "RESET_VERIFIED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"


class Cd101WriteState(StrEnum):
    """Single-shot CD101 request totals (no AUTHORIZE)."""

    STATUS_OBSERVED = "STATUS_OBSERVED"
    CD101_BLOCK_BUILT = "CD101_BLOCK_BUILT"
    CD101_AUTHORIZED_FOR_SINGLE_WRITE = "CD101_AUTHORIZED_FOR_SINGLE_WRITE"
    CD101_TRANSMITTED = "CD101_TRANSMITTED"
    ACK_RECEIVED = "ACK_RECEIVED"
    ACK_TIMEOUT = "ACK_TIMEOUT"
    DC101_OBSERVED = "DC101_OBSERVED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"


class ReturnStatusResetWriteState(StrEnum):
    """Office-capture path: CD1 RETURN_STATUS then CD1 RESET."""

    FILLING_COMPLETE = "FILLING_COMPLETE"
    RETURN_STATUS_TRANSMITTED = "RETURN_STATUS_TRANSMITTED"
    RETURN_STATUS_ACK = "RETURN_STATUS_ACK"
    MID_STATUS_POLLED = "MID_STATUS_POLLED"
    RESET_TRANSMITTED = "RESET_TRANSMITTED"
    RESET_ACK = "RESET_ACK"
    RESET_VERIFIED = "RESET_VERIFIED"
    REFUSED = "REFUSED"
    FAULT = "FAULT"
