"""Normalized InteliPump pump events."""

from __future__ import annotations

from enum import StrEnum


class PumpEvent(StrEnum):
    COMMUNICATION_STARTED = "COMMUNICATION_STARTED"
    COMMUNICATION_LOST = "COMMUNICATION_LOST"
    PUMP_DISCOVERED = "PUMP_DISCOVERED"
    CONFIGURATION_MISSING = "CONFIGURATION_MISSING"
    RESET_OBSERVED = "RESET_OBSERVED"
    READY_OBSERVED = "READY_OBSERVED"
    NOZZLE_LIFTED = "NOZZLE_LIFTED"
    NOZZLE_RETURNED = "NOZZLE_RETURNED"
    NOZZLE_SELECTION_CHANGED = "NOZZLE_SELECTION_CHANGED"
    NOZZLE_STATUS_OBSERVED = "NOZZLE_STATUS_OBSERVED"
    AUTHORIZATION_CONFIRMED = "AUTHORIZATION_CONFIRMED"
    FILLING_STARTED = "FILLING_STARTED"
    FILLING_UPDATED = "FILLING_UPDATED"
    FILLING_COMPLETED = "FILLING_COMPLETED"
    LIMIT_REACHED = "LIMIT_REACHED"
    SUSPENDED_OBSERVED = "SUSPENDED_OBSERVED"
    RESUMED_OBSERVED = "RESUMED_OBSERVED"
    FAULT_OBSERVED = "FAULT_OBSERVED"
    FAULT_CLEARED = "FAULT_CLEARED"
    MAINTENANCE_ENTERED = "MAINTENANCE_ENTERED"
    MAINTENANCE_EXITED = "MAINTENANCE_EXITED"
    SWITCHED_OFF_OBSERVED = "SWITCHED_OFF_OBSERVED"
    UNKNOWN_OBSERVATION = "UNKNOWN_OBSERVATION"
